default: &default
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/orangesys/thanos-operator
  environment:
    GO111MODULE: "on"

version: 2

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "go/pkg/mod"
      - run: make docker-build
      
          
    