default: &default
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/orangesys/thanos-operator
  environment:
    GO111MODULE: "on"

version: 2

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install kubebuilder
          command: |
            export os=$(go env GOOS)
            export arch=$(go env GOARCH)
            curl -sL https://go.kubebuilder.io/dl/2.0.0-alpha.4/${os}/${arch} | tar -xz -C /tmp/
            sudo mv /tmp/kubebuilder_2.0.0-alpha.4_${os}_${arch} /usr/local/kubebuilder
            export PATH=$PATH:/usr/local/kubebuilder/bin >> ~/.BASH_ENV
      - run: make docker-build
      - run: docker images
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make docker-push
      
          
    